version: '3.8'

services:
  # Service pour l'application Node.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=camet_user
      - DB_PASSWORD=camet_password
      - DB_NAME=camet_db
    depends_on:
      - db

  # Service pour la base de données MySQL
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=camet_db
      - MYSQL_USER=camet_user
      - MYSQL_PASSWORD=camet_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: